# Generated by Django 6.0.3 on 2026-03-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_excelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excel_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.excelfile'),
        ),
    ]
