# Generated by Django 6.0.3 on 2026-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_product_excel_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='excel_file_id',
        ),
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
